### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by nathanvercaemert** [covah901/Dactyl-Manuform-Blackpill#1]
Should this still work? I'm getting all sorts of errors when I try to "qmk compile -kb keyboard/f401 -km default". This is after copying the contents of 'qmk firmware' into a 'keyboard' folder that I created in the actual 'qmk firmware/keyboards' repository. This is exactly what I'm trying to build, and I'm hopeful I can get some help! I have a very customized Ergodox EZ firmware, but the hand-wire process is new to me.

**Comment by covah901** [comment]
I have not kept up with qmk for a while now. I'm guessing this approach might have become outdated by now. The best place to find help would be the qmk discord.
